### ISSUE TITLE
Package import errors

### ISSUE THREAD

**Issue by sweverett** [superbit-collaboration/superbit-metacal#56]
When running on a HPC cluster, currently the code will fail if not built from `setup.py`, e.g.:
```
Traceback (most recent call last):
  File "pipe_test.py", line 6, in <module>
    import utils
  File "/projects/superbit/repos/superbit-metacal/superbit_lensing/utils.py", line 6, in <module>
    import superbit_lensing as sb
ModuleNotFoundError: No module named 'superbit_lensing'
```

As this kind of setup was initially made for a defunct testing schema, I think we should remove this to make sure we're running w/ the correct code. We can rethink about a proper module install later

**Comment by sweverett** [comment]
Nevermind - this was already solved using the solution described [here](https://stackoverflow.com/a/50194143/1222951).

Forgot that relative imports from parent directories are no longer allowed in python 3.3+. We will continue w/ the `setup.py` file & a `pip` install w/ `-e`
