### ISSUE TITLE
Pipe test currently fails in `master`

### ISSUE THREAD

**Issue by sweverett** [superbit-collaboration/superbit-metacal#57]
I'm about to start a new branch for a quick update, but noticed that `pipe_test.py` currently fails on `master` during the PSF stage:

```
...
Making PSF models...
Traceback (most recent call last):
  File "/Users/sweveret/repos/superbit-metacal/superbit_lensing/medsmaker/superbit/medsmaker_mocks.py", line 650, in _select_stars_for_psf
    ss = Table.read(sscat,hdu=2)
  File "/Users/sweveret/miniconda3/envs/sbmcal/lib/python3.7/site-packages/astropy/table/connect.py", line 61, in __call__
    out = registry.read(cls, *args, **kwargs)
  File "/Users/sweveret/miniconda3/envs/sbmcal/lib/python3.7/site-packages/astropy/io/registry.py", line 520, in read
    data = reader(*args, **kwargs)
  File "/Users/sweveret/miniconda3/envs/sbmcal/lib/python3.7/site-packages/astropy/io/fits/connect.py", line 231, in read_table_fits
    astropy_native=astropy_native)
  File "/Users/sweveret/miniconda3/envs/sbmcal/lib/python3.7/site-packages/astropy/io/fits/connect.py", line 218, in read_table_fits
    raise ValueError("No table found")
ValueError: No table found
```

I can't tell if this is due to one of our recent PR merges that had to do w/ the stellar sample selection. @mcclearyj thoughts?

**Comment by sweverett** [comment]
Update: I did not encounter this error when running `python pipe_test.py --fresh`, so there may be some broken logic somewhere when some files are already present
